language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      install: ./.travis/deps-x86_64-linux.sh
      script: ./.travis/build-x86_64-linux.sh
    - os: osx
      sudo: false
      osx_image: xcode9.2
      install: ./.travis/deps-x86_64-macos.sh
      script: ./.travis/build-x86_64-macos.sh
