language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      install: ./.travis/build-x86_64-linux/deps.sh
      script: ./.travis/build-x86_64-linux/build.sh
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      install: ./.travis/test-a64-on-x86_64-linux/deps.sh
      script: ./.travis/test-a64-on-x86_64-linux/build.sh
    - os: osx
      sudo: false
      osx_image: xcode9.2
      install: ./.travis/build-x86_64-macos/deps.sh
      script: ./.travis/build-x86_64-macos/build.sh
